### ISSUE TITLE
Unable to find file or directory './bjsmc-ie8.eot' in the build folder.

### ISSUE THREAD

**Issue by Goaty89** [Ziggeo/ziggeo-client-sdk#1]
I try to import the and use the css with webpack. It comes out with. Cannot resolve 'file' or 'directory' ./bjsmc-ie8.eot in '../build'.

**Comment by oliverfriedmann** [comment]
Can you give it another try with the newest commit?

**Comment by Goaty89** [comment]
I try npm install and npm update again, seem like the files that you updated not updating at my side.

**Comment by oliverfriedmann** [comment]
This should be resolved now, please pull the newest version.

**Comment by Goaty89** [comment]
Nope, i try npm install, it not update the file's you updated. Could it be the versioning?

**Comment by oliverfriedmann** [comment]
Which version are you being shown when you look at ziggeo.js ? What version are you specifying in your package.json?

**Comment by Goaty89** [comment]
it is ziggeo-client-sdk@0.0.24.
Inside the ziggeo.js file show `ziggeo-js-sdk - v0.0.24 - 2017-03-15`, which i think it still the old version. I saw in here was changed to `ziggeo-js-sdk - v0.0.24 - 2017-03-30`.

**Comment by oliverfriedmann** [comment]
Please try changing the SEMVER in your package.json from 0.0.24 to 0.0.25.

**Comment by Goaty89** [comment]
Awesome! It is working now. Thanks!

**Comment by oliverfriedmann** [comment]
Great to hear that!
