### ISSUE TITLE
Event 'processed' not triggered when recording a video

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#12]
Hey guys

I've got an another problem. The event 'processed' doesn't trigger if I directly record a video. If I upload one it's working.

Is this a bug?

Thank you for your help!

**Comment by Bane-D** [comment]
Hi,

Are you using r31 or older revision? Prior to r31 the `processing` and `processed` events would not always fire, only when needed.

With v2 on r31 we are firing them all the time and there it should work.

* Still good to mention, the same will not fire if Flash is used.

Hope this helps.

Regards,
Bane

**Comment by zyph00** [comment]
Hey

I'm using v2-stable. Both events 'processing' and 'processed' aren't firing. So I'm using 'verified' to check if the video is ready to save but I think it's not as safe as the event 'processed' would be.

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

Actually the "verified" event is the best to know that video can be saved. We have a quick check algorithm that runs before processing that knows if the video would be possible to process or not.

If it is, the verified event fires confirming it.

As soon as the verified event fires, you would know that it is good to be saved.

Stable, which is equal to r30 at this time is still not firing processing events. If you were to switch to r31 instead, they should fire.

Still, I would still suggest using `verified` event.

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Thank you for your help!

I've got an another question/problem with the processing event. Currently I'm using the 'verified' event (as you stated) and it's working good. But the problem is now that after the verification the processing starts and sometimes it takes longer than a minute for a video with just 5 seconds and not such a big resolution.

So for what exactly is the processing event and can I disable this if it's not needed? Or do you have an idea how I could speed up that process?

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

Glad to hear that it is working good for you :)

Generally as soon as the verified event fires, you can remove the embedding or take your customer to a new page, etc. Verified event tells you that our system got the video and that it will be able to transcode it. Unless you want to wait for everything that follows, you do not need to.

While you do not need to destroy it, you could also just hide it if you preferred and then show it later once `ready_to_play` event for example fires, telling you that the player with the video is available.

Hope this helps :)

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Cool, thank you!

I think I will try it this way.

So (hopefully) my last question: The verifying process takes sometimes very long. Why does this happen? Or is it a limitation of my Ziggeo test account?

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

You are welcome. Please do let me know how it goes :)

Free account does not have limitations in place in regards to the same.

Verification would depend on the size of the original video. The algorithm that does the check is designed to be very quick, however it would also depend on several other parameters next to size.

For example, a quick list:
1. codec used when encoding the video that is sent to our servers
2. bitrate
3. resolution

Depending on first, it might take it a bit longer for case A than case B.

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Cool, thank you.

I've changed the video profile a bit and I think this helps a lot. So it's working super fine! 👍 

Regards,
Thomas
