### ISSUE TITLE
How to get URL of the thumbnail?

### ISSUE THREAD

**Issue by Goaty89** [Ziggeo/ziggeo-client-sdk#2]
I try the version 1 which allow to get URL of the thumbnail. Version 2 here seem like this function gone. Or is it use another method to get the image?

**Comment by oliverfriedmann** [comment]
Let's assume that application is a variable holding your v2 application instance. Then application.videos.imageUrl(token) should return the image url for the video.

**Comment by Goaty89** [comment]
It is working with 
`
const app = new Ziggeo.V2.application(...)
console.log(app.videos.imageUrl(videoToken));`

else can use the manual way to direct call 'http://location/(ZiggeoToken)/video/(VideoToken)'.
Thanks for the solution.
