### ISSUE TITLE
Cannot read property 'get' of undefined Error

### ISSUE THREAD

**Issue by rouvenherzog** [Ziggeo/ziggeo-client-sdk#23]
Hey there,

We are using the react-ziggeo wrapper to record and play videos on our platform. Sometimes we are getting a exception report about `Cannot read property 'get' of undefined`.

Unfortunately, I can only give you the line numbers of the bundled application. I hope that helps anyhow. Please find attached a screenshot of the stacktrace as well.

```
// In Line 10890
{snip} ion(e){return this.__properties.hasKey(e)},get:function(e){return this.__properties.get(e)},setProp:function(e,t){return this.__properties.s {snip}
```

<img width="883" alt="Screenshot 2019-05-07 at 08 44 12" src="https://user-images.githubusercontent.com/1587774/57277391-5684c500-70a4-11e9-875b-c591cc1fb767.png">

The exception has been thrown on a Mac OSX 10.14.4, using Chrome version 74.0.3729.

Is there anything we can do about this?

Have a great day

**Comment by csillero** [comment]
Hi Rouven,

Let me first mention that I work at Ziggeo. 

Could you share a page or a link so we can try to reproduce and troubleshoot?

Thanks.

**Comment by Bane-D** [comment]
Hi Rouven,

Hope you are enjoying your day. I wanted to recheck with you about the issue you had reported. Unfortunately we can not recreate it on our side in our testes.

The link to the page would be best. It is understandable that you might not be able to do that, in which case it would be great if you can pass us the code your are using.

For example if this is happening when recording only, could you send us just the recorder related code? Likewise if it is happening when you try to play the video, the code for player.

This might help us to recreate the same on our end and find out what is happening.

Regards,
Bane

**Comment by ntshcalleia** [comment]
Closing due to lack of response.
