### ISSUE TITLE
"Error" events

### ISSUE THREAD

**Issue by katrevich** [Ziggeo/ziggeo-client-sdk#24]
For some reason, when I'm using a widget as a popup with only upload option available and try to upload something other than a video file, an error event is not triggered. I can see POST error (412 Precondition Failed) in the console and a widget is just stuck at "Preparing covershots".

Version of the ziggeo sdk is 2.34.1.

Initialized with these parameters:

`new ZiggeoApi.V2.PopupRecorder({
            attrs: {
                timelimit: 180,
                allowrecord: false,
                allowupload: true,
                manualupload: true,
                flashincognitosupport: true,
                forceoverwrite: true,
                responsive: true,
                rerecordable: false,
                customcovershots: false,
                localplayback: false,
            },
        })`

**Comment by sambua** [comment]
Hello @katrevich , 

Thanks a lot that informed us. It's new feature to get snapshots from uploaded video file so we will improve it. Could you please try to set `picksnapshots: false` while we will fix it? But in this case it will not prepare cover shot images for uploaded normal video files.

**Comment by sambua** [comment]
@katrevich will be better to add `allowedextensions` settings this should run `FatalError`

**Comment by katrevich** [comment]
@sambua Yeah good idea should have had it from the start :)

The widget still hangs even with picksnapshots set to false, so if you rename any file to an appropriate extension the problem is still there.

**Comment by zamirkhan** [comment]
We're having this issue too. Is there an event we can use to become aware of this error?

Legitimate use-case:
- User visits widget on their phone
- Selects upload
- From phone native menu, selects their camera
- Takes a picture instead of a video, selects "OK"
- Widget accepts the upload as if nothing is wrong
- Widget is stuck on "Verifying" forever

We see a 412 Error, but not an event we can listen for.
