### ISSUE TITLE
stretch parameter not working well.

### ISSUE THREAD

**Issue by Goaty89** [Ziggeo/ziggeo-client-sdk#3]
I use the code below it show in short-while and then the whole player gone. Once remove the stretch, it show and working but not fill the size i assign in the element.

`showPlayer (videoId) {
    const player = new window.ZiggeoApi.V2.Player({
      element: document.getElementById(elemId),
      attrs: {
        stretch: true,
        responsive: true,
        theme: 'modern-green',
        video: videoId
      }
    });`

How do the video fill up the size that assign through the `div`?

**Comment by Bane-D** [comment]
Hi,

Sorry for the wait, I do suggest in future to send us an email to our support channel or go here: https://support.ziggeo.com/hc/en-us/requests/new

Now you seem to be interested in the player taking full with and full height of the element and it is not doing so. Can you tell us if:
1. video itself is not grabbing complete width and height, rather it is padded on sides however player is taking complete width and height
2. player is not taking complete width and height of the element it is in

Also, with `stretch` parameter, I was not able to recreate the same, however I would be happy to look further into it. Could you please tell us if this is still happening for you and if you have any events associated with player such as "ended"? (just to see if there might be some code that makes it "gone".

Would be good to know if by gone it completely is removed from page, hidden or something else happens instead?

**Comment by Goaty89** [comment]
Hi Bane,


I have roughly know how it not showing.


In the code i do have the code
 `<div id="ziggeoApp"  style"height:'100%';"></div>`
then the `stretch` not showing the player.

I change it  `<div id="ziggeoApp"  style"min-height: 300px; height: 100%;"></div>`
It comes out an empty space in between.

Hope this will help on investigate.

Thanks and regards,
Charles
________________________________

**Comment by ntshcalleia** [comment]
Closing this as `stretch` parameter has been deprecated. The player now stretches to fill the whole container by default.
