### ISSUE TITLE
[Android] [Firefox] Microphone indicator stay red even tho the sound recording is working

### ISSUE THREAD

**Issue by katrevich** [Ziggeo/ziggeo-client-sdk#38]
SDK version is 2.34.14
Tested in Android 6 + Firefox 68.7.0
Also tested on Android 6 + Chrome 80.0.3989.119 - same behavior

Sound records in both cases but the indicator stay red.

webrtc_streaming_if_necessary and webrtc_on_mobile are set to true

**Comment by Bane-D** [comment]
Hi, thank you for the naming and details, really helpful.

The sound indicator is working by doing periodic checks. At specific time it checks if there is sound present and based on the same changes the indicator. Of course, even though it is periodic, it should show right, so I am passing this to my colleague working on this aspect of our system.

Can you tell us if you are experiencing the same maybe with the latest 2.35.13 as well?

Regards,
Bane

**Comment by katrevich** [comment]
Hi, thanks for quick reply :) 
I bumped the SDK version to 2.35.13. Now mic icon becomes green almost immediately in firefox, but stay red on Chrome
https://imgur.com/a/aZc633w

**Comment by Bane-D** [comment]
Thank you for testing with the latest version and glad to hear that it is working as expected on Firefox.

I am asking one of my colleagues that would know more about this to check it out however just to help him, I would like to confirm that this is still just a "cosmetic" issue, where audio is captured properly, just the indicator stays red.

Also just to confirm that this happens only on Android, not on your desktop Chrome for example.

Best,
Bane

**Comment by katrevich** [comment]
Sorry for taking so long to respond :)
based on my testing it's just a cosmetic issue, recordings are fine. It's just a concern that it might confuse end-users

**Comment by Bane-D** [comment]
All good :) My colleague put this on his list and is something that we look to recreate and sort out by the end of this week / start of next one :)

Best,
Bane

**Comment by katrevich** [comment]
Hey, any updates on the issue?

**Comment by sambua** [comment]
hello @katrevich should be fixed with the latest release `2.35.19`, could you please check and advice ?

**Comment by katrevich** [comment]
@sambua  Yap, we checked it and everything seems to be in order. Thanks :) 
The issue can be closed now

**Comment by sambua** [comment]
thanks @katrevich !
