### ISSUE TITLE
Unminified Source

### ISSUE THREAD

**Issue by andriasang** [Ziggeo/ziggeo-client-sdk#4]
Are you able to include the unminified source code in the repo?  It would help with debugging, and we may want to fork it to do customizations for our use case.

Thanks!

**Comment by oliverfriedmann** [comment]
We are working on a self-compile version of the library. We'll update this issue as soon as you can test it out.

**Comment by andriasang** [comment]
Great!  Thanks, and keep up the great work on the product!

**Comment by oliverfriedmann** [comment]
Done.
