### ISSUE TITLE
Update and proofread translations

### ISSUE THREAD

**Issue by ntshcalleia** [Ziggeo/ziggeo-client-sdk#41]
Ziggeo currently supports 30 different languages and we’re really proud of that! We want to make our software accessible to as many people as possible. Unfortunately keeping all of those translations updated as we add new features can be quite overwhelming, so we’re asking for your help!

As you can see from the [original English strings](/Ziggeo/ziggeo-client-sdk/blob/master/dist/english.yml) and the [locale files](/Ziggeo/ziggeo-client-sdk/tree/master/src/locales), most translations are missing something. We’re looking to update them to include all strings listed on the English file.

To open a PR you just need to follow these instructions:

- Files should be in UTF-8 format
- Do not change the string labels, only the actual string
- Write a comment here telling us which language you’re working on

**Couldn’t find your language?** We’d love to support it as well! Feel free to open a PR for a new language following the same instructions above. The file name should be the [language’s ISO 639-1 code](https://gist.github.com/Josantonius/b455e315bc7f790d14b136d61d9ae469).

**Comment by jikuja** [comment]
I can work with Finnish(fi) translation. I'll check it later today.

**Comment by ColinFrick** [comment]
I'd like to work on the German (de) translation.

**Comment by ntshcalleia** [comment]
Thanks, @jikuja!

@ColinFrick sure, go ahead! Thank you as well. 🙂

**Comment by lisabecker** [comment]
I'd like to contribute Dutch (nl).

**Comment by fuadreza** [comment]
I would like to contribute on Indonesian (id) translation. Thank you

**Comment by ntshcalleia** [comment]
@lisabecker @fuadreza Sure! Thank you. 🙂

**Comment by idanyman** [comment]
I'll update the Swedish translations! (sv)

**Comment by printf-ana** [comment]
Hey, i'm finishing the translate for portuguese. =)

**Comment by ntshcalleia** [comment]
Thanks, @printf-ana! Are you working on the pt or pt-br translation?

**Comment by enzomzaocv** [comment]
I would like to add the missing lines on the spanish translation.

**Comment by philrussel21** [comment]
Greetings! I'd like to work on the missing lines for the Tagalog (tl) language.

**Comment by vale-c** [comment]
Hi! Can I please work on the Italian? Thank you! :)

**Comment by princezna** [comment]
Hi, I'd like to add Czech (cs) translation.

**Comment by krisfremen** [comment]
Hi there, I'd like to translate in Macedonian.

Cheers!

**Comment by Vhizux** [comment]
I'd like to update Polish (PL) translation

**Comment by GETYAMAME** [comment]
Hello, I've added a Japanese translation.
