### ISSUE TITLE
Issue with latest version of edge - windows 10

### ISSUE THREAD

**Issue by martinbooth** [Ziggeo/ziggeo-client-sdk#5]
There's an issue loading the ziggeo client sdk on the latest version of edge that was rolled out with the windows 10 creators update recently.

The library fails to load with the error: Unable to get property 'extend' of undefined or null reference.

Unfortunately it is almost impossible for me to debug this issue as I only have access to the minified source however a couple of things that may help:

The issue disappears if you open the developer tools which suggests it may be caused by a bug with an optimisation done by edge only when the developer tools are closed.

I think that the issue may be with the tool you've used to package up the code. I believe an array of dependencies is empty which is being passed into a define statement, but I'm not sure on this.

Finally, your own website is affected too (not just ours) so I don't think it's anything we've done wrong

Here's a simple repro
```
<head>
  <script>
    window.onerror = (msg, url, lineNo, columnNo, error) => {
      alert(error);
    }

    </script>
    <script src="ziggeo.js"></script> 
</head>
```
![edge error](https://user-images.githubusercontent.com/4383362/28196126-1e9beeb6-6881-11e7-8995-1bb31d3322c5.png)

Martin

**Comment by oliverfriedmann** [comment]
We are currently working on a fix.

**Comment by mahipalsingh** [comment]
Any updates on this issue??

**Comment by sambua** [comment]
Hi @mahipalsingh,

This issue has been already solved. If you still have an issue, please could you provide? :

1. With Ziggeo settings/options, you're using.
2. Browser/OS version.

Thanks in advance.
Rashad

**Comment by mahipalsingh** [comment]
It was an error with me using the older version (r26) in my case. Switched to current stabled version and it works now. Thanks for the assist.

**Comment by Bane-D** [comment]
Hi Mahipal,

Great to hear that it is working properly for you in the stable revision now.

If you have anything else that you would like to let us know or want to ask about, please do feel free to reach out.

Regards,
Bane
