### ISSUE TITLE
Not possible to import with Webpack

### ISSUE THREAD

**Issue by oskarer** [Ziggeo/ziggeo-client-sdk#60]
When importing Ziggeo with Webpack;

`import ziggeo from 'ziggeo-client-sdk/build/ziggeo';`

It cannot compile due to `with` is used, which is forbidden in strict mode; https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with.

```
Failed to compile.

./node_modules/ziggeo-client-sdk/build/ziggeo.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/xxx/node_modules/ziggeo-client-sdk/build/ziggeo.js: 'with' in strict mode (7:1003705)
```

I did a little digging and it looks like some of the `betajs` libraries are using `with`, do you have any ideas how to get around this problem?

**Comment by oskarer** [comment]
Related: https://github.com/Ziggeo/react-ziggeo/pull/39

**Comment by sambua** [comment]
Hi @oskarer , unfortunately for now we don't have any way how to fix `strict mode`, reason is we are still supporting IE8.

**Comment by oskarer** [comment]
@sambua @Bane-D I understand, can you give me any pointers how I could fork and fix this myself?

**Comment by oskarer** [comment]
The problem for me that I'm using https://github.com/rails/webpacker which runs all node_modules packages through Babel. Had to exclude `ziggeo-client-sdk`; https://github.com/rails/webpacker/blob/54c3ca9245e9ee330f8ca63b447c202290f7b624/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader.

**Comment by Bane-D** [comment]
Hi Oskar,

I wanted to follow up here to let you know that we have removed the use of `with(obj)` which should now allow you to use our code within strict mode as well. :)
