### ISSUE TITLE
Unable to find the keys for localization on Website.

### ISSUE THREAD

**Issue by gitSambhal** [Ziggeo/ziggeo-client-sdk#62]
Page: https://ziggeo.com/docs/sdks/javascript/browser-integration/localization

Section: Language keys and their values

So previously I think there was a section containing all the localization  keys with there values that we can use to change text but now that list on not showing. Please check and share the correct place to look for all localization keys.

**Comment by ntshcalleia** [comment]
Hi @gitSambhal, you're right, there should be a list with all keys and values on that page. We're looking into it, in the meantime you can find all localization strings [here](https://github.com/Ziggeo/ziggeo-client-sdk/tree/master/src/locales) and [here](https://github.com/betajs/betajs-media-components/tree/master/src/locales).

**Comment by gitSambhal** [comment]
What is the key for "The video is processing - stay tuned." ? I am not able to find.

**Comment by ntshcalleia** [comment]
Hi @gitSambhal, it's `ziggeoplayer.video-processing`.
English strings are on the following files:
https://github.com/Ziggeo/ziggeo-client-sdk/blob/master/dist/english.yml
https://github.com/betajs/betajs-media-components/blob/master/dist/english.yml

**Comment by gitSambhal** [comment]
> Hi @gitSambhal, it's `ziggeoplayer.video-processing`.
> English strings are on the following files:
> https://github.com/Ziggeo/ziggeo-client-sdk/blob/master/dist/english.yml
> https://github.com/betajs/betajs-media-components/blob/master/dist/english.yml

I tried it but it is not working.

**Comment by ntshcalleia** [comment]
Hi @gitSambhal, I was able to change it with the following line of code:
`ZiggeoApi.V2.Locale.mainLocale.register({"ziggeoplayer.video-processing": "Hello world"}, 10);`

Strings that start with "ziggeo" are on the `mainLocale`, while the strings that come from BetaJS are registered on `mediaLocale`.

About the localization table on the docs page, it has been fixed and should be visible now. 🙂
