### ISSUE TITLE
[Player] Unable to set default pop-up audio

### ISSUE THREAD

**Issue by GETYAMAME** [Ziggeo/ziggeo-client-sdk#64]
I set up a pop-up to play a video, and by default, the video plays without sound. 
How can I set it so that it plays with sound when it pops up? 
I tried setting the embed parameter "volume", but it did not work.

https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters#javascript-revision=stable

**Comment by Bane-D** [comment]
Hi there,

The autoplay in browsers always comes with few requirements or if you prefer limitations to keep in mind.

* Please note that these are not limitations nor requirements of our system, rather from browser vendors.

1. Autoplay is quite often used for ads to show up, so they are not getting much "love" from browser side
2. When autoplay is enabled, and there is no user interaction before the video playback the browser inner code might stop something from happening. This can be for many reasons (to stop ads from being annoying, to save battery power on "likely" unneeded content, etc.). This can also be stopping entire video playback or just muting the audio.
3. When autoplay is set with 100% volume it might be stopped (some browsers)
4. When autoplay is set at 50% volume some browsers will allow it
5. Generally ideal way for autoplay to start is to follow some user interaction
6. Autoplay works better on video that is larger (example 640x480) compared to video that is smaller in size (for example 100x100), connecting to the first point in this list. The size of the video is also relative to its position and placement on the page (main section, side of the page, etc.)

So if you are using our popup then the audio should be followed after the click and should generally be allowed. If you are using your own popup that is shown on page load, consider changing the volume to 20-50% and also to require some action like click from your customer.

Hope this helps :)

**Comment by GETYAMAME** [comment]
Hello.
Thank you for your reply.

I see that it was a specification on the browser side that the pop-up didn't have a sound from the beginning.
It was helpful.I'm going to close this issue because it's not Ziggeo's issue.
