### ISSUE TITLE
[requirement] add config 'forceWebrtc' to support special scene

### ISSUE THREAD

**Issue by songzhj** [Ziggeo/ziggeo-client-sdk#66]
Hello !

  We are using Ziggeo Recorder. Our page is in Electron which is load by 'file://' protocol.
  After Chrome disable Flash (we are upgraded Electron 10 from Electron 4), we can't use Recorder.
  Because we use 'file://' protocol load page from local, ziggeo-client-sdk judge it doesn't support webrtc in such page (but it is actually supported).
  So Could Ziggeo Dev Team add a config to use webrtc forcely or support file protocol when judge supported?

Looking forward for any reply!

**Comment by Bane-D** [comment]
Hi,

Thank you for bringing this to our attention. It is added on our todo list and we will add or rather remove this check from our system.

Leaving this open until it is added and pushed when we will update you about the same.

Regards,
Bane
