### ISSUE TITLE
ios run failed: The following build commands failed: CompileC ZiggeoRN

### ISSUE THREAD

**Issue by ChenDimri** [Ziggeo/ziggeo-client-sdk#69]
Hi, I'm getting this error when trying to run ios. (pod install working successfully)

** BUILD FAILED **

The following build/Users/chend/newproject/ios/Podfile commands failed:
        CompileC /Users/chend/Library/Developer/Xcode/DerivedData/newproject-frskhpfjqawsajelejzwsthvdxyd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ZiggeoRN.build/Objects-normal/x86_64/RCTZiggeoRecorder.o /Users/chend/newproject/node_modules/react-native-ziggeo-library/ios/Recorder/RCTZiggeoRecorder.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/chend/Library/Developer/Xcode/DerivedData/newproject-frskhpfjqawsajelejzwsthvdxyd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ZiggeoRN.build/Objects-normal/x86_64/RCTVideos.o /Users/chend/newproject/node_modules/react-native-ziggeo-library/ios/Videos/RCTVideos.m normal x86_64 o/Users/chend/newproject/ios/Podfile.lockbjective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**This is my code:**

**### Podfile:**
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'newproject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
  target 'newprojectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#     end
#   end
# end

target 'newproject-tvOS' do
  # Pods for newproject-tvOS

  target 'newproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

**### Podfile.lock:**
PODS:
  - boost-for-react-native (1.63.0)
  - CocoaAsyncSocket (7.6.5)
  - CocoaLibEvent (1.0.0)
  - DoubleConversion (1.1.6)
  - FBLazyVector (0.63.3)
  - FBReactNativeSpec (0.63.3):
    - Folly (= 2020.01.13.00)
    - RCTRequired (= 0.63.3)
    - RCTTypeSafety (= 0.63.3)
    - React-Core (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - Flipper (0.54.0):
    - Flipper-Folly (~> 2.2)
    - Flipper-RSocket (~> 1.1)
  - Flipper-DoubleConversion (1.1.7)
  - Flipper-Folly (2.3.0):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.20)
  - Flipper-Glog (0.3.6)
  - Flipper-PeerTalk (0.0.4)
  - Flipper-RSocket (1.1.1):
    - Flipper-Folly (~> 2.3)
  - FlipperKit (0.54.0):
    - FlipperKit/Core (= 0.54.0)
  - FlipperKit/Core (0.54.0):
    - Flipper (~> 0.54.0)
    - FlipperKit/CppBridge
    - FlipperKit/FBCxxFollyDynamicConvert
    - FlipperKit/FBDefines
    - FlipperKit/FKPortForwarding
  - FlipperKit/CppBridge (0.54.0):
    - Flipper (~> 0.54.0)
  - FlipperKit/FBCxxFollyDynamicConvert (0.54.0):
    - Flipper-Folly (~> 2.2)
  - FlipperKit/FBDefines (0.54.0)
  - FlipperKit/FKPortForwarding (0.54.0):
    - CocoaAsyncSocket (~> 7.6)
    - Flipper-PeerTalk (~> 0.0.4)
  - FlipperKit/FlipperKitHighlightOverlay (0.54.0)
  - FlipperKit/FlipperKitLayoutPlugin (0.54.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutTextSearchable
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutTextSearchable (0.54.0)
  - FlipperKit/FlipperKitNetworkPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitReactPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitUserDefaultsPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/SKIOSNetworkPlugin (0.54.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitNetworkPlugin
  - Folly (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - Folly/Default (= 2020.01.13.00)
    - glog
  - Folly/Default (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - GoogleAds-IMA-iOS-SDK (3.11.3)
  - iOS-Client-SDK (1.1.27):
    - GoogleAds-IMA-iOS-SDK (= 3.11.3)
  - OpenSSL-Universal (1.0.2.20):
    - OpenSSL-Universal/Static (= 1.0.2.20)
  - OpenSSL-Universal/Static (1.0.2.20)
  - RCTRequired (0.63.3)
  - RCTTypeSafety (0.63.3):
    - FBLazyVector (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTRequired (= 0.63.3)
    - React-Core (= 0.63.3)
  - React (0.63.3):
    - React-Core (= 0.63.3)
    - React-Core/DevSupport (= 0.63.3)
    - React-Core/RCTWebSocket (= 0.63.3)
    - React-RCTActionSheet (= 0.63.3)
    - React-RCTAnimation (= 0.63.3)
    - React-RCTBlob (= 0.63.3)
    - React-RCTImage (= 0.63.3)
    - React-RCTLinking (= 0.63.3)
    - React-RCTNetwork (= 0.63.3)
    - React-RCTSettings (= 0.63.3)
    - React-RCTText (= 0.63.3)
    - React-RCTVibration (= 0.63.3)
  - React-callinvoker (0.63.3)
  - React-Core (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.3)
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/CoreModulesHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/Default (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/DevSupport (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.3)
    - React-Core/RCTWebSocket (= 0.63.3)
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - React-jsinspector (= 0.63.3)
    - Yoga
  - React-Core/RCTActionSheetHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTAnimationHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTBlobHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTImageHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTLinkingHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTNetworkHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTSettingsHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTTextHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTVibrationHeaders (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-Core/RCTWebSocket (0.63.3):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.3)
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-jsiexecutor (= 0.63.3)
    - Yoga
  - React-CoreModules (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.3)
    - React-Core/CoreModulesHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-RCTImage (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-cxxreact (0.63.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-callinvoker (= 0.63.3)
    - React-jsinspector (= 0.63.3)
  - React-jsi (0.63.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-jsi/Default (= 0.63.3)
  - React-jsi/Default (0.63.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
  - React-jsiexecutor (0.63.3):
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
  - React-jsinspector (0.63.3)
  - react-native-flipper (0.113.0):
    - React-Core
  - React-RCTActionSheet (0.63.3):
    - React-Core/RCTActionSheetHeaders (= 0.63.3)
  - React-RCTAnimation (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.3)
    - React-Core/RCTAnimationHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTBlob (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - React-Core/RCTBlobHeaders (= 0.63.3)
    - React-Core/RCTWebSocket (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-RCTNetwork (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTImage (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.3)
    - React-Core/RCTImageHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - React-RCTNetwork (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTLinking (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - React-Core/RCTLinkingHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTNetwork (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.3)
    - React-Core/RCTNetworkHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTSettings (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.3)
    - React-Core/RCTSettingsHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - React-RCTText (0.63.3):
    - React-Core/RCTTextHeaders (= 0.63.3)
  - React-RCTVibration (0.63.3):
    - FBReactNativeSpec (= 0.63.3)
    - Folly (= 2020.01.13.00)
    - React-Core/RCTVibrationHeaders (= 0.63.3)
    - React-jsi (= 0.63.3)
    - ReactCommon/turbomodule/core (= 0.63.3)
  - ReactCommon/turbomodule/core (0.63.3):
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-callinvoker (= 0.63.3)
    - React-Core (= 0.63.3)
    - React-cxxreact (= 0.63.3)
    - React-jsi (= 0.63.3)
  - Yoga (1.14.0)
  - YogaKit (1.18.1):
    - Yoga (~> 1.14)
  - ZiggeoRN (1.4.3):
    - iOS-Client-SDK
    - React-Core

DEPENDENCIES:
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)
  - FBReactNativeSpec (from `../node_modules/react-native/Libraries/FBReactNativeSpec`)
  - Flipper (~> 0.54.0)
  - Flipper-DoubleConversion (= 1.1.7)
  - Flipper-Folly (= 2.3.0)
  - Flipper-Glog (= 0.3.6)
  - Flipper-PeerTalk (~> 0.0.4)
  - Flipper-RSocket (~> 1.1)
  - FlipperKit (~> 0.54.0)
  - FlipperKit/Core (~> 0.54.0)
  - FlipperKit/CppBridge (~> 0.54.0)
  - FlipperKit/FBCxxFollyDynamicConvert (~> 0.54.0)
  - FlipperKit/FBDefines (~> 0.54.0)
  - FlipperKit/FKPortForwarding (~> 0.54.0)
  - FlipperKit/FlipperKitHighlightOverlay (~> 0.54.0)
  - FlipperKit/FlipperKitLayoutPlugin (~> 0.54.0)
  - FlipperKit/FlipperKitLayoutTextSearchable (~> 0.54.0)
  - FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)
  - FlipperKit/FlipperKitReactPlugin (~> 0.54.0)
  - FlipperKit/FlipperKitUserDefaultsPlugin (~> 0.54.0)
  - FlipperKit/SKIOSNetworkPlugin (~> 0.54.0)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - iOS-Client-SDK (from `https://github.com/Ziggeo/iOS-Client-SDK.git`)
  - RCTRequired (from `../node_modules/react-native/Libraries/RCTRequired`)
  - RCTTypeSafety (from `../node_modules/react-native/Libraries/TypeSafety`)
  - React (from `../node_modules/react-native/`)
  - React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)
  - React-Core (from `../node_modules/react-native/`)
  - React-Core/DevSupport (from `../node_modules/react-native/`)
  - React-Core/RCTWebSocket (from `../node_modules/react-native/`)
  - React-CoreModules (from `../node_modules/react-native/React/CoreModules`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - react-native-flipper (from `../node_modules/react-native-flipper`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - ReactCommon/turbomodule/core (from `../node_modules/react-native/ReactCommon`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)
  - ZiggeoRN (from `../node_modules/react-native-ziggeo-library`)

SPEC REPOS:
  trunk:
    - boost-for-react-native
    - CocoaAsyncSocket
    - CocoaLibEvent
    - Flipper
    - Flipper-DoubleConversion
    - Flipper-Folly
    - Flipper-Glog
    - Flipper-PeerTalk
    - Flipper-RSocket
    - FlipperKit
    - GoogleAds-IMA-iOS-SDK
    - OpenSSL-Universal
    - YogaKit

EXTERNAL SOURCES:
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  FBLazyVector:
    :path: "../node_modules/react-native/Libraries/FBLazyVector"
  FBReactNativeSpec:
    :path: "../node_modules/react-native/Libraries/FBReactNativeSpec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  iOS-Client-SDK:
    :git: https://github.com/Ziggeo/iOS-Client-SDK.git
  RCTRequired:
    :path: "../node_modules/react-native/Libraries/RCTRequired"
  RCTTypeSafety:
    :path: "../node_modules/react-native/Libraries/TypeSafety"
  React:
    :path: "../node_modules/react-native/"
  React-callinvoker:
    :path: "../node_modules/react-native/ReactCommon/callinvoker"
  React-Core:
    :path: "../node_modules/react-native/"
  React-CoreModules:
    :path: "../node_modules/react-native/React/CoreModules"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  react-native-flipper:
    :path: "../node_modules/react-native-flipper"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  ReactCommon:
    :path: "../node_modules/react-native/ReactCommon"
  Yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"
  ZiggeoRN:
    :path: "../node_modules/react-native-ziggeo-library"

CHECKOUT OPTIONS:
  iOS-Client-SDK:
    :commit: 57a8cc6e258f195eb3c9cafe66af9742046e840d
    :git: https://github.com/Ziggeo/iOS-Client-SDK.git

SPEC CHECKSUMS:
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  CocoaAsyncSocket: 065fd1e645c7abab64f7a6a2007a48038fdc6a99
  CocoaLibEvent: 2fab71b8bd46dd33ddb959f7928ec5909f838e3f
  DoubleConversion: cde416483dac037923206447da6e1454df403714
  FBLazyVector: 878b59e31113e289e275165efbe4b54fa614d43d
  FBReactNativeSpec: 7da9338acfb98d4ef9e5536805a0704572d33c2f
  Flipper: be611d4b742d8c87fbae2ca5f44603a02539e365
  Flipper-DoubleConversion: 38631e41ef4f9b12861c67d17cb5518d06badc41
  Flipper-Folly: e4493b013c02d9347d5e0cb4d128680239f6c78a
  Flipper-Glog: 1dfd6abf1e922806c52ceb8701a3599a79a200a6
  Flipper-PeerTalk: 116d8f857dc6ef55c7a5a75ea3ceaafe878aadc9
  Flipper-RSocket: a3acb8812d6adf127deb0a5edae2793b97e6b641
  FlipperKit: ab353d41aea8aae2ea6daaf813e67496642f3d7d
  Folly: b73c3869541e86821df3c387eb0af5f65addfab4
  glog: 40a13f7840415b9a77023fbcae0f1e6f43192af3
  GoogleAds-IMA-iOS-SDK: 134b35758455576aaa6b3d2d3146699dcf8af4f1
  iOS-Client-SDK: 412f588cdfeb407885b4e9d6c3322d2f6f275a04
  OpenSSL-Universal: ff34003318d5e1163e9529b08470708e389ffcdd
  RCTRequired: 48884c74035a0b5b76dbb7a998bd93bcfc5f2047
  RCTTypeSafety: edf4b618033c2f1c5b7bc3d90d8e085ed95ba2ab
  React: f36e90f3ceb976546e97df3403e37d226f79d0e3
  React-callinvoker: 18874f621eb96625df7a24a7dc8d6e07391affcd
  React-Core: ac3d816b8e3493970153f4aaf0cff18af0bb95e6
  React-CoreModules: 4016d3a4e518bcfc4f5a51252b5a05692ca6f0e1
  React-cxxreact: ffc9129013b87cb36cf3f30a86695a3c397b0f99
  React-jsi: df07aa95b39c5be3e41199921509bfa929ed2b9d
  React-jsiexecutor: b56c03e61c0dd5f5801255f2160a815f4a53d451
  React-jsinspector: 8e68ffbfe23880d3ee9bafa8be2777f60b25cbe2
  react-native-flipper: 2a212eb0fead9ae9b42d1eb75604757cdf36f2bb
  React-RCTActionSheet: 53ea72699698b0b47a6421cb1c8b4ab215a774aa
  React-RCTAnimation: 1befece0b5183c22ae01b966f5583f42e69a83c2
  React-RCTBlob: 0b284339cbe4b15705a05e2313a51c6d8b51fa40
  React-RCTImage: d1756599ebd4dc2cb19d1682fe67c6b976658387
  React-RCTLinking: 9af0a51c6d6a4dd1674daadafffc6d03033a6d18
  React-RCTNetwork: 332c83929cc5eae0b3bbca4add1d668e1fc18bda
  React-RCTSettings: d6953772cfd55f2c68ad72b7ef29efc7ec49f773
  React-RCTText: 65a6de06a7389098ce24340d1d3556015c38f746
  React-RCTVibration: 8e9fb25724a0805107fc1acc9075e26f814df454
  ReactCommon: 4167844018c9ed375cc01a843e9ee564399e53c3
  Yoga: 7d13633d129fd179e01b8953d38d47be90db185a
  YogaKit: f782866e155069a2cca2517aafea43200b01fd5a
  ZiggeoRN: f4db8a0ccde6f1ee509e1134efd43caa80a61768

PODFILE CHECKSUM: 74fa27552e85a2c434d1a4a24f5eb5c5d1b78b62

COCOAPODS: 1.10.0

**Comment by Bane-D** [comment]
Hi Chen,

Thank you for posting a lot of details in regards to your issue. I will however close it seems as if it is off topic from what I can tell for our Client SDK that is used only within browsers as alternative to our pre-built JS SDK.

Instead, what I would like to ask you is to open the issue here: https://github.com/Ziggeo/ReactNativeSDK/issues

This will then pop up to my colleagues working on React Native instead and they will be able to understand what is happening and how to best assist you with the same.

Thank you for your understanding :)
