### ISSUE TITLE
Moderation issue with native capture (params?)

### ISSUE THREAD

**Issue by Textras** [Ziggeo/ziggeo-client-sdk#7]
We are creating our video integration test with the Ziggeo API using following: 

According to your docs, 'create': https://ziggeo.com/docs/sdks/javascript/api 

We capture the video with native video recorder then give recorded video file passing here with filesObject

`var videoObject = {
    'file': filesObject,
    'min_duration': 0,
    'max_duration': 15,
    'tags':'share',
    'volatile': true
}
    ZiggeoApi.Videos.create(videoObject, {`

and create success callback calling

`ZiggeoApi.Videos.update(videoToken , {submitted:true,approved:true}, {`

and thus we get a success on the update. 

But seems here we are missing some params to be sent on create. After having reviewed the docs, we are not sure what those are. Any guidance would be much appreciated. Although in the Ziggeo dashboard we see (after setting the videos to approved), that they are, we are tying to do this by defaults so no upload requires any moderation. Currently the videos tell us they require moderation and to contact support.

See the list of params here, https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters#javascript-revision=v1-stable&javascript-version=v1
but is there required ones we are not or incorrectly using? 

(@oliverfriedmann any ideas?) Thanks.

**Comment by Bane-D** [comment]
When a video is recorded, by default it will not be neither approved nor rejected. So you would always need to change the status of the video.

Having that said, you can set up your app to show or to refuse to show videos that are not approved, so I think that this is causing the issues.

To make sure this is not the case, you would:
1. log into your Ziggeo account
2. click on the application that you are using
3. go to *Manage* sub menu
4. there click on the *Authorization Settings* section
5. On this segment you should see the option *Client cannot view unaccepted videos* make sure that this is *unchecked*.
6. click on *Save* button under it

If unchecked, you would see all videos. If it is checked however you could only see the videos once they are approved.

Hope this helps, of course please let us know how it goes :)

**Comment by Textras** [comment]
Hello thanks for the response. Actually we have 'client cannot view unaccepted videos' unchecked already. I am mobile so let's see how this formatting goes;

    // mediaFiles[i] is catured video file which is taken by native video recoreder.
    var path = mediaFiles[i].fullPath;

    //Making object as API for create required according to https://ziggeo.com/docs/sdks/javascript/api
    var videoObject = {
        'file': mediaFiles[i],
        'min_duration': 0,
        'max_duration': 15,
        'tags':'share',
        'volatile': true
    }
    // calling create video
    ZiggeoApi.Videos.create(videoObject, {
        success: function (args, result) {
            //Success create
            console.log("Success to create");

            // Sending token for update for submitter and approved to avaoid moderation error.
            var videoToken = result.token;
            ZiggeoApi.Videos.update(videoToken , {submitted:true,approved:true}, {
                success: function (args, result) {
                    //Success Update
                    console.log("Success for update");
                },
                failure: function (args, error) {
                    console.log("Fail to update");
                }
            });
        },
        failure: function (args, error) {
            console.log('fail to create ');
        }
    });


    This Above code we called and get success in create and also success for update. We area updating with submitted and approved true and got success response.

    And Ziggeo account -->  Default ---> Events i can see both above the call.
    Can you please guide me where i am going wrong or if anything is missing so we can overcome "Moderation error" ?

https://ziggeo.com/docs/sdks/javascript/api

Also yes we are using Native video capture. Here is some code we are using;

```
var captureSuccess = function(mediaFiles) {
    var i, path, len;
    for (i = 0, len = mediaFiles.length; i < len; i += 1) {
        path = mediaFiles[i].fullPath;
        var videoObject = {
            'file': mediaFiles[i],
            'min_duration': 0,
            'max_duration': 15,
            'tags':'share',
            'volatile': true
        }
        ZiggeoApi.Videos.create(videoObject, {
            success: function (args, result) {
                var videoToken = result.token;
                ZiggeoApi.Videos.update(videoToken , {submitted:true,approved:true}, {
                    success: function (args, result) {
                        var videoMessage = "<ziggeo ziggeo-video='" + videoToken + "' ziggeo-width=200 ziggeo-height=150></ziggeo>";
                        // var videoMessage = "<ziggeo ziggeo-video='" + result.token + "'></ziggeo>";

                    },
                    failure: function (args, error) {
                        console.log('Something went wrong. Please try again...');
                    }
                });
            },
            failure: function (args, error) {
                console.log('Something went wrong. Please try again...');
            }
        });
    }
};

// capture error callback
var captureError = function(error) {
    navigator.notification.alert('Error code: ' + error.code, null, 'Capture Error');
};
setTimeout(function(){
    navigator.device.capture.captureVideo(captureSuccess, captureError, {duration:15});
},3000)
```
Here is and example video file object which is capture from Native video capture;
---
mediaFiles[i] have value {"name":"VID_20171124_110337730.mp4","localURL":"cdvfile://localhost/persistent/DCIM/Camera/VID_20171124_110337730.mp4","type":"video/mp4","lastModified":null,"lastModifiedDate":1511501627000,"size":16507880,"start":0,"end":0,"fullPath":"file:///storage/emulated/0/DCIM/Camera/VID_20171124_110337730.mp4"}

**Comment by Textras** [comment]
Hi Bane, thanks for the call. Posted below into the Skype chat for more dynamic issue solving. We are almost always on. But sending here to keep as a ticket reference. Also just want to add Bane, that we resolved the Socket.IO<http://socket.io/> issue and still not getting the stream token and getting the same error. Naitik has added some helpful markup with comments for the cordova guys of what we suspect trouble spots.

Again, thanks for the help and look fwd to chatting soon.; ttys

Naitik's Markup below:


// Setting full path of captured video file like "file:///storage/emulated/0/DCIM/Camera/VID_20171127_230243822.mp4"

var path = mediaFiles[i].fullPath;

var videoObject = {

'file': path,

'min_duration': 0,

'max_duration': 15,

'tags':'share',

'volatile': true

}


//calling create API with above video object

ZiggeoApi.Videos.create(videoObject, {

success: function (args1, result1) {

// Got video token

var videoToken = result1.token;

ZiggeoApi.Streams.create(videoToken , videoObject, {

success: function (args2, result2) {

// as args2 we get video token of created and as result2 we get the same object values which we sent in videoObject for create video

//Not getting stream token as we expected here that need to be submitted in ZiggeoApi.Streams.accept(); as argument.

ZiggeoApi.Streams.accept();

//Create message and send to chat

var videoMessage = "<ziggeoplayer ziggeo-video='" + videoToken + "' ziggeo-width='200' ziggeo-height='150' ziggeo-theme='modern' ziggeo-themecolor='red'></ziggeoplayer>";

},

failure: function (args, error) {

console.log('Something went wrong. Please try again...');

}

});

},

failure: function (args, error) {

console.log('Something went wrong. Please try again...');

}

});




Get Outlook for Android<https://aka.ms/ghei36>

________________________________
