### ISSUE TITLE
Transcoding make file corrupted

### ISSUE THREAD

**Issue by aravindhandysolver** [Ziggeo/ziggeo-client-sdk#71]
Video getting corrupted on using transcoding. Video wont display and its not getting transcoded also. Need urgent fix for this. Multiple videos got corrupted because of this.

**Comment by Bane-D** [comment]
Hi @aravindhandysolver it might be best if you reach out to us over email: support@ziggeo.com with the video tokens in question so that we can check them out.

**Comment by jukoen** [comment]
+1, support has my details & tokens.

**Comment by aravindhandysolver** [comment]
Dear Sir,

I would like to share the token and video link with you for your reference.
Because of transcoding video got corrupted.

Token : 14ee2771dc7d916951ef079*

Video Link {removed}



Best wishes,
*A. Aravind Menon*
Web Developer

**Comment by Bane-D** [comment]
Hi Aravind,

I see that you have reached out to us over the email thread as well. The support thread is actually the recommended way to report the issue with any video. While it might not be working for you right away, if we are able to fix it, then the video would be available over direct link - which sometimes might not be desirable.

We will update you there as we have more details.
