### ISSUE TITLE
Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'

### ISSUE THREAD

**Issue by freitasskeeled** [Ziggeo/ziggeo-client-sdk#76]
Hi,

This is the same issue as this one https://github.com/Ziggeo/react-ziggeo/issues/102. 
I'm creating one here because I believe the bug is in the JS SDK since it happens using the `vue-ziggeo` package.

browser: Chrome Version 111.0.5563.65 (Official Build) (64-bit)
vue-ziggeo: 2.3.1

![image](https://user-images.githubusercontent.com/29863364/225650387-269c60fe-1ada-46a3-8f68-69cddddda03f.png)

Note: works fine in Firefox

**Comment by gopal-augment** [comment]
@freitasskeeled same here. Reported to the support team, but they won't take it as seriously.

**Comment by sambua** [comment]
Hi all, we've published a new release 2.42.2. As it's not stable for now we're not upgraded SDKs. But you always can do it manually. Here's documentation where you can upgrade to the newest release https://github.com/Ziggeo/vue-ziggeo#upgrade-ziggeo-sdk

**Comment by gopal-augment** [comment]
@sambua We are using Angular SDK, and the version older than 2.42.2 has the same issues([Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'](https://github.com/Ziggeo/ziggeo-client-sdk/issues/76#top). In the 2.42.2 version, video playback is not working giving 410 HTTP errors. Also, the SDK doesn't work smoothly.

**Comment by sambua** [comment]
Hello @gopal-augment what type of HTTP errors you're getting, could you please share here? 

It could be related your setups.

As per documentation `410 Gone client error response code indicates that access to the target resource is no longer available at the origin serve`

**Comment by sambua** [comment]
@gopal-augment Please don't share here any sensitive information, please remove before them if there're any.

**Comment by gopal-augment** [comment]
@sambua I don't understand what is the sensitive information here. I just report with error I got.

**Comment by gopal-augment** [comment]
> Hello @gopal-augment what type of HTTP errors you're getting, could you please share here?
> 
> It could be related your setups.
> 
> As per documentation `410 Gone client error response code indicates that access to the target resource is no longer available at the origin serve`

@sambua 
If it is in our steps, then why it is playing fine after a few minutes using the same code setups?

**Comment by sambua** [comment]
I mean maybe you're using [auth tokens](https://ziggeo.com/docs/api/authorization-tokens/create-and-use/)  https://ziggeo.com/docs/api/authorization-tokens/ that sensitive information I meant. 

So your code is working as expected on previous releases, and you're getting 410 error in the newest one?

**Comment by gopal-augment** [comment]
In the older version, getting "`Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive`'"
On newer version getting 410

**Comment by gopal-augment** [comment]
![image](https://user-images.githubusercontent.com/31436402/225703749-7a756bb8-206d-4c3e-beb2-39f270870911.png)

 Chrome browser Faces issues all time. Firefox occurs sometimes.

**Comment by sambua** [comment]
@gopal-augment could you please install the lates `angular-ziggeo@4.0.1` and reply?

**Comment by freitasskeeled** [comment]
Hi all,

So we ran some tests based on your input @sambua . 
We are using the vue-ziggeo for Vue 2 (version: 2.3.1). 

I followed the instructions from [here](https://github.com/Ziggeo/vue-ziggeo/tree/7932156f9453ffa08425cf76f194ce41c777001f) and updated the SDK package to version 2.42.2 in our devDependencies. 

Results:

- Firefox: recorder keeps crashing looping
- Chrome: recorder keeps crashing with permissions error (even though it has) 

Any suggestions?

**Comment by gopal-augment** [comment]
> @gopal-augment could you please install the lates `angular-ziggeo@4.0.1` and reply?

@sambua 
Same error " _An error occurred, please try again later. Click to retry._ " and 410 HTTP error.

Additionally, I got this error in the browser console.

`VM6:3 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at t.get (ziggeo.js:7:301352)
    at t.<anonymous> (ziggeo.js:7:1413922)
    at ziggeo.js:7:141779
    at Array.forEach (<anonymous>)
    at n (ziggeo.js:7:141757)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1704:33)`

**Comment by sambua** [comment]
@gopal-augment could you please type in the console and advice what you're seeing?

`ZiggeoApi.V2.Device.info.revision`

@freitasskeeled will preoare a new release and let you know. After please you let me know what you got.

**Comment by gopal-augment** [comment]
> @gopal-augment could you please type in the console and advice what you're seeing?
> 
> `ZiggeoApi.V2.Device.info.revision`
>


@sambua 

`{version: 1, revision: 42, latest: true, prerelease: true}`

**Comment by gopal-augment** [comment]
`<video controls>
    <source src="ZIGGEO_VIDEO_URL" type="video/mp4">
</video>`
**ZIGGEO_VIDEO_URL without `?force_refresh=false`**
@sambua 
I tried this code to inspect and replace the Ziggeo SDK video tag in the browser. It is working fine. Not sure, but this may help.

**Comment by sambua** [comment]
@gopal-augment , actually you should see `{version: 1, revision: 39, latest: true, prerelease: false}` . As Angular package is not builds with Ziggeo modules, and loads from separately. 

As a temporarily solution I'm passing zipped [ziggeo.js.zip](https://github.com/Ziggeo/ziggeo-client-sdk/files/11001956/ziggeo.js.zip) which you can replace with stable r39 in node_modules and build with that one.

**Comment by gopal-augment** [comment]
@sambua Yes, that js works for the new video recording and its playback. But before the recorded video still getting the same 410 error and message

**Comment by gopal-augment** [comment]
Also, local playback is not available. Once submitted it gets start processing and shows the text processing. Can't able to play local video.

**Comment by sambua** [comment]
@freitasskeeled sorry, couldn't be able publish a new release for the Vue 2 as it's older version and there's some trouble on node version conflicts. 

As you environment already support it, please you can just upgrade to the latest `ziggeo-client-sdk` release `v2.42`, or download stable JS version from message above (https://github.com/Ziggeo/ziggeo-client-sdk/issues/76#issuecomment-1473871910 ) . 

If you'll face with any trouble please write here, will try to support.

**Comment by PeopleRPM** [comment]
This issue started to return after upgrading chrome to Version 111.0.5563.65 on 3/15/2023.

Everyone using this version gets the stop() error because the "state" is inactive. Everyone using older versions like 109.*** the error is not returned.

In my case, this error resulted in several calls from our customers, the emergency solution was to download "https://assets.ziggeo.com/v2-stable/ziggeo.js" and change:

this._mediaRecorder.stop(), at line 10525 to:
(this._mediaRecorder.state !== 'inactive' ? this._mediaRecorder.stop() : true),

I will suggest the upgrade.

**Comment by PeopleRPM** [comment]
This issue started to return after upgrading chrome to Version 111.0.5563.65 on 3/15/2023.

Everyone using this version gets the stop() error because the "state" is inactive. Everyone using older versions like 109.*** the error is not returned.

In my case, this error resulted in several calls from our customers, the emergency solution was to download "https://assets.ziggeo.com/v2-stable/ziggeo.js" and change:

this._mediaRecorder.stop(), at line 10525 to:
(this._mediaRecorder.state !== 'inactive' ? this._mediaRecorder.stop() : true),

I will suggest the upgrade.

**Comment by PeopleRPM** [comment]
> @gopal-augment , actually you should see `{version: 1, revision: 39, latest: true, prerelease: false}` . As Angular package is not builds with Ziggeo modules, and loads from separately.
> 
> As a temporarily solution I'm passing zipped [ziggeo.js.zip](https://github.com/Ziggeo/ziggeo-client-sdk/files/11001956/ziggeo.js.zip) which you can replace with stable r39 in node_modules and build with that one.

I saw now that I already had an alternative. Thanks.

**Comment by freitasskeeled** [comment]
> @freitasskeeled sorry, couldn't be able publish a new release for the Vue 2 as it's older version and there's some trouble on node version conflicts.
> 
> As you environment already support it, please you can just upgrade to the latest `ziggeo-client-sdk` release `v2.42`, or download stable JS version from message above ([#76 (comment)](https://github.com/Ziggeo/ziggeo-client-sdk/issues/76#issuecomment-1473871910) ) .
> 
> If you'll face with any trouble please write here, will try to support.

We already tried to install version 2.42 of the SDK into our `devDependencies` and also manually replacing the dist file in our `node_modules` with the one provided.
Both options result in a recorder crash loop in Firefox and an error related with browser permissions in Chrome.
Both tests done in private mode.

Please let us know of any alternative solutions.

**Comment by freitasskeeled** [comment]
@sambua after retesting from a clean copy of our app, clean install, etc, we found that the "crash loop" issue was on our side and not related with the suggested fix.

However, we confirmed that changing the SDK in the devDependencies did not fixed the issue for us. 
We managed to fix the issue by using a local copy of the vue-ziggeo package and making the change suggested by @PeopleRPM .

We understand that the vue2 version of the package might have maintenance issues but let us know if it is possible to "refresh it" and make a new build available with the issue fixed.

Cheers

**Comment by sambua** [comment]
Hi @freitasskeeled , could you please try test attached .tgz file. Please download it, put in any folder in your comp 

[vue2-ziggeo-2.4.1.tgz](https://github.com/Ziggeo/ziggeo-client-sdk/files/11032879/vue2-ziggeo-2.4.1.tgz)

after in your app package.json please replace `vue-ziggeo` version part with full local path to this .tgz file. After re-build. 
example: `"vue-ziggeo": "path_to/vue2-ziggeo-2.4.1.tgz"`

As I don't have local app for testing it wasn't tested. Please after let me know result, thanks in advance!

**Comment by HelenaJM** [comment]
It seems that the issue with stopping recording was solved but now we're seeing a lot of sessions where the following happens: 

1.  user clicks "Record" to initiate a recording session. The video recorder is loaded.
2. User clicks "Record in the player area. Then Ziggeo displays "WS_connection [object Event]" error inside the player. Then the user clicks the message but then Ziggeo just appears to be loading. At some point, ziggeo appears to be back to normal (or sometimes users have reloaded the page). 
3. User clicks "REcord" in the ziggeo player and the video appears to be recorded normally. HOWEVER, nothing is actually properly uploaded (can't validate in AWS right now myself) but the result is an "empty video" - we can display the embedded video area as if there was something but there is a 0 length video only.
In the session log, there is no failed API call to/from ziggeo - I can only find these issues per user reports or when combing through the sessions because this error is not logged properly.

We applied the patch for the stopping of video but now this issue is running rampant and it seems to be for those on Chrome 111.0.0.
We have advised people to use Firefox and pre-record and upload but this is not feasible.

**Comment by freitasskeeled** [comment]
> Hi @freitasskeeled , could you please try test attached .tgz file. Please download it, put in any folder in your comp
> 
> [vue2-ziggeo-2.4.1.tgz](https://github.com/Ziggeo/ziggeo-client-sdk/files/11032879/vue2-ziggeo-2.4.1.tgz)
> 
> after in your app package.json please replace `vue-ziggeo` version part with full local path to this .tgz file. After re-build. example: `"vue-ziggeo": "path_to/vue2-ziggeo-2.4.1.tgz"`
> 
> As I don't have local app for testing it wasn't tested. Please after let me know result, thanks in advance!

Hi @sambua ,

We replaced the package with the vue2-ziggeo you provided but the app stops working. Exception below:

![image](https://user-images.githubusercontent.com/29863364/227507594-32c20c0b-df76-4769-93c5-1926479296cb.png)

If would make it easier if you created a vue 2 dummy project on your side to validate these solutions please.

Best regards,
Freitas

**Comment by Bane-D** [comment]
Hello,

Thank you for the feedback Freitas, we are looking into this (creating Vue 2 specific SDK update), will need to reach out one we know more about this.

Helena, thank you for reaching out about this however the issue you have mentioned is different so I would like to ask you if you could open a new issue instead that is focused on the WS Connection error that you have.

Also it would be good to confirm if this WS error is happening for you in Chrome or in Safari as we do expect that this issue is sometimes present in Safari, which we are currently looking into.

**Comment by HelenaJM** [comment]
> Hello,
> 
> Thank you for the feedback Freitas, we are looking into this (creating Vue 2 specific SDK update), will need to reach out one we know more about this.
> 
> Helena, thank you for reaching out about this however the issue you have mentioned is different so I would like to ask you if you could open a new issue instead that is focused on the WS Connection error that you have.
> 
> Also it would be good to confirm if this WS error is happening for you in Chrome or in Safari as we do expect that this issue is sometimes present in Safari, which we are currently looking into.

This is mostly Chrome 111.0.0. But we've seen instances on Safari, too. 
What is suspicious is that it suddenly became rampant for a certain group of users. But it's intermittent, so it's not easy to pinpoint for us when exactly it's happening. But for a certain group, Ziggeo is effectively unusable in our app on their device right now - they can neither upload nor record without the video getting lost. The URL does not contain the video. So it looks like after the WS error, ziggeo leaves the user with impression that they can record but in reality the video is never saved.

**Comment by freitasskeeled** [comment]
@Bane-D any update on this issue?

**Comment by Bane-D** [comment]
Hi Rui,

Yes, this should be resolved with r42, although I would personally recommend going with latest r43 as it includes additional fixes.

Versions that include fixes for above:
2.42.3
2.43.1 and 2.43.2

* Of course all future versions/revisions will as well.

**Comment by gopal-augment** [comment]
> @gopal-augment , actually you should see `{version: 1, revision: 39, latest: true, prerelease: false}` . As Angular package is not builds with Ziggeo modules, and loads from separately.
> 
> As a temporarily solution I'm passing zipped [ziggeo.js.zip](https://github.com/Ziggeo/ziggeo-client-sdk/files/11001956/ziggeo.js.zip) which you can replace with stable r39 in node_modules and build with that one.

Hi @sambua 
If I use this JS file, can't able to select the camera/audio input source. `outsource-selectors` is nothing listed in the dropdown.
If I remove the Trim option it is playing fine in an angular and got the `outsource-selectors` list.
`{version: 1, revision: 42, latest: true, prerelease: true}`

**Comment by Bane-D** [comment]
Hi Gopal,

That file was a quick patch crated at that time, however does not include all of the fixes that our JS SDK does, so please use the latest version of r42 or even better r43 in your app.

If you have any issues at that time with the same, do let us know, however it should no longer be connected to the what was reported on this issue.
