### ISSUE TITLE
recorder: input_bind only works once

### ISSUE THREAD

**Issue by aerickson** [Ziggeo/ziggeo-client-sdk#8]
Expected:
  - clicking 'Redo' should empty out the bound field
  - recording a new video should populate the bound field

What happens:
  - The field is set on the initial recording, but clicking 'Redo' doesn't clear the field and recording a new video doesn't set the field.

**Comment by Bane-D** [comment]
Hi,

Thank you for reporting this to us. We are looking into it for you.

At this time I can suggest using `verified` event instead and then adding the code within it to populate the desired field or fields. By doing this you would be doing the same thing as if you were using our input_bind property, while it also allows you to add any other actions, or update multiple fields in the same time.

Of course this is just a suggestion until the proper fix is in place for this in our system.

Regards,
Bane

**Comment by oliverfriedmann** [comment]
Should be fixed.
