### ISSUE TITLE
'Events' Attribute missing on the ZiggeoApi object when using v2

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#9]
Hey guy's.

I've got a problem with v2 of ziggeo.

Following is my case:

I'm using ziggeo from that url: 
`//assets-cdn.ziggeo.com/v2-stable/ziggeo.js`

I initialise it with the following code:
```
new ZiggeoApi.V2.Application({
    token: {TOKEN},
    language: {LANGUAGE},
    webrtc_streaming: true
});
```
And if I output 'ZiggeoApi' the following appears:
![screen shot 2018-03-23 at 18 35 40](https://user-images.githubusercontent.com/8693771/37844772-129b2046-2ec9-11e8-98b3-3539a98ed176.png)

So the main problem is now that 'Events' doesnt exist in the object. And if I use the following code which I got from your site (Here: https://ziggeo.com/docs/sdks/javascript/browser-integration/embed-methods#javascript-version=v2) with that at the beginning: 
```
ZiggeoApi.Events.on("system_ready", function() {
```
... it doesn't work and produces an error. Because of the missing 'Events' Attribute I'm also not able to use any other functionality which is connected with events.

When I change the version to 'v1-stable' in the url it's working. 

Is this a bug or what am I doing wrong?

**Comment by ibnutri** [comment]
Hi There,

It's not a bug but rather a different approach between V1 and V2. And V2 is using "ready" event instead of "system_ready"
You can try this sample below and let us know how it goes

```javascript
var application = new ZiggeoApi.V2.Application({
    token: {TOKEN},
    language: {LANGUAGE},
    webrtc_streaming: true
});
application.on('ready', function(){
    // your code here
});
```

**Comment by Bane-D** [comment]
Hi,

Just jumping in here to mention that we are revising our docs and the update that shows pure v2 codes will follow soon.

Thank you again for reporting it. We will update this post as soon as new docs are out.

Regards,
Bane

**Comment by zyph00** [comment]
Hey guy's.

Thank you for the fast answer. It's working perfectly! I'm very happy :).

Cheers
